import { Injectable } from '@angular/core';
import { LowMedHigh } from './enums';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor() { }

  // CONTINUOUS
  public getContinuousData(): any[] {
    return [
      {
        category: 'Alzheimer\'s disease',
        publicationYear: 1997, firstAuthor: 'Evans', studyName: 'Unknown', country: 'US', context: ['H'],
        period: [1982, 1987],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 642,
        baselineFemalePercentage: 56.4,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [4.3, 'average 4.3'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 95,
        measureOfEffect: ['OR'],
        adjustedFor: 'follow-up interval, age, sex, occupation, income',
        effectSize: [0.85, 0.75, 0.95],
        weight: 8.01
      },
      {
        publicationYear: 2001, firstAuthor: 'Tyas', studyName: 'MSHA', country: 'CA', context: ['H'],
        period: [1991, 1997],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 694,
        baselineFemalePercentage: 62.4,
        sampleAgeMean: '74.0 (5.8)',
        baselineEducation: '10.6 (3.2)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 36,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex',
        effectSize: [0.86, 0.76, 0.96],
        weight: 8.14
      },
      {
        publicationYear: 2002, firstAuthor: 'Kukull', studyName: 'ACT', country: 'US', context: ['H'],
        period: [1994, 2000],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2356,
        baselineFemalePercentage: 59.0,
        sampleAgeMean: '79.4 w/ dementia<br/>74.0 w/o dementia',
        baselineEducation: '12.8 w/ dementia<br/>13.9 w/o dementia',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'presume 4'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 151,
        measureOfEffect: ['RaR'],
        adjustedFor: 'age, sex, APOE',
        effectSize: [0.91, 0.86, 0.97],
        weight: 16.1
      },
      {
        publicationYear: 2002, firstAuthor: 'Lindsay', studyName: 'CSHA', country: 'CA', context: ['H'],
        period: [1992, 1996],
        studyType: ['CC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 4088,
        baselineFemalePercentage: 58.0,
        sampleAgeMean: '81.0 cases<br/>72.9 controls',
        baselineEducation: '9.9 cases<br/>11.1 controls',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 194,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex, education',
        effectSize: [0.92, 0.88, 0.97],
        weight: 18.35
      },
      {
        publicationYear: 2008, firstAuthor: 'Lee', studyName: 'KYS', country: 'KR', context: ['H'],
        period: [1996, 2003],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 658,
        baselineFemalePercentage: 57.7,
        sampleAgeMean: '72.2 (5.6)',
        baselineEducation: '2.5 (3.5)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [5.4, '5.4 (1.6)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 74,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, literacy',
        effectSize: [0.85, 0.74, 0.98],
        weight: 6.26
      },
      {
        publicationYear: 2014, firstAuthor: 'Borenstein', studyName: 'Kame', country: 'US', context: ['H'],
        period: [1992, 2001],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['Ja-Am'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 1836,
        baselineFemalePercentage: 61.8,
        sampleAgeMean: '77.1 (7.4) cases<br/>71.4 (5.4) other',
        baselineEducation: '11.7 (2.9) cases<br/>13.0 (2.9) other',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 4,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 135,
        measureOfEffect: ['HR'],
        adjustedFor: 'age',
        effectSize: [0.92, 0.84, 1.01],
        weight: 10.91
      },
      {
        publicationYear: 2017, firstAuthor: 'Yu', studyName: 'MAP', country: 'US', context: ['H'],
        period: [1997, 2004],
        studyType: ['PC'],
        sampling: ['V'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [58.8, 100.2],
        contributingNumber: 805,
        baselineFemalePercentage: 76.7,
        sampleAgeMean: '81.5 (7.7)',
        baselineEducation: '15.3 (3.0)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 8,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 102,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, total literacy',
        effectSize: [1.04, 0.97, 1.12],
        weight: 13.99
      },
      {
        publicationYear: 2018, firstAuthor: 'Hendrie', studyName: 'IIDP', country: 'US', context: ['H'],
        period: [1992, 2009],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['Af-Am'],
        sampleAgeRecruited: [70, 100],
        contributingNumber: 3276,
        baselineFemalePercentage: 65.5,
        sampleAgeMean: '77.7 (5.9) 1992 cohort<br/>77.2 (5.5) 2001 cohort',
        baselineEducation: '9.3 (3.1) 1992 cohort<br/>11.4(2.7) 2001 cohort',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 7,
        followUpYears: [17, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 233,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, rural vs urban residence, 2001 vs 1992 cohort',
        effectSize: [0.91, 0.87, 0.96],
        weight: 18.24
      },
      {
        isAverageRow: true,
        effectSize: [0.92, 0.88, 0.95, true], // true indicates this is an average of other values
      },
      {
        category: 'All dementia',
        publicationYear: 1994, firstAuthor: 'Stern', studyName: 'Unknown', country: 'US', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['V', 'mixed'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [60, 99],
        contributingNumber: 583,
        baselineFemalePercentage: 72.9,
        sampleAgeMean: '74.0 (7.6)',
        baselineEducation: '9.6 (4.7)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 4,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 106,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender',
        effectSize: [0.92, 0.88, 0.95],
        weight: 15.06
      },
      {
        publicationYear: 1997, firstAuthor: 'Schmand - A', studyName: 'AMSTEL', country: 'NL', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2063,
        baselineFemalePercentage: 62.6,
        sampleAgeMean: '74.1 (5.5) normal <br/>77.5 cases (5.0)',
        baselineEducation: '9.1 (3.0) normal <br/>8.0 (1.8) cases',
        usedDiagnosticCriteria: false,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 152,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, gender, pre-morbid intelligence, occupation, comorbidity, family history',
        effectSize: [0.86, 0.57, 1.31],
        weight: 0.20
      },
      {
        publicationYear: 2002, firstAuthor: 'Kukull', studyName: 'ACT', country: 'US', context: ['H'],
        period: [1994, 2000],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2356,
        baselineFemalePercentage: 59.0,
        sampleAgeMean: '79.4 w/ dementia<br/>74.0 w/o dementia',
        baselineEducation: '12.8 w/ dementia<br/>13.9 w/o dementia',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'presume 4'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 215,
        measureOfEffect: ['RaR'],
        adjustedFor: 'age, sex, APOE',
        effectSize: [0.94, 0.90, 0.99],
        weight: 11.23
      },
      {
        publicationYear: 2010, firstAuthor: 'Kerola', studyName: 'Kuopio 75+', country: 'FI', context: ['H'],
        period: [1998, 2003],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 303,
        baselineFemalePercentage: 72.0,
        sampleAgeMean: '80 (approx)',
        baselineEducation: '7 (approx)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 59,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, hypertension, B-type natriuretic peptide',
        effectSize: [0.50, 0.33, 0.77],
        weight: 0.20
      },
      {
        publicationYear: 2010, firstAuthor: 'Brayne', studyName: 'EClipSE - CFAS, CC75C, Vantaa 85+', country: 'FI-GB', context: ['H'],
        period: [1985, 2005],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 872,
        baselineFemalePercentage: 68.0,
        sampleAgeMean: '90 (68-107)',
        baselineEducation: 'median 9 (range 0-24)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 7,
        followUpYears: [20, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 486,
        measureOfEffect: ['OR'],
        adjustedFor: 'age at death, sex, study',
        effectSize: [0.89, 0.83, 0.94],
        weight: 7.46
      },
      {
        publicationYear: 2012, firstAuthor: 'Katz', studyName: 'EAS', country: 'US', context: ['H'],
        period: [1993, 2009],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [70, 100],
        contributingNumber: 1168,
        baselineFemalePercentage: 60.7,
        sampleAgeMean: '78.8 (5.42)',
        baselineEducation: '13.5 (3.50)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 16,
        followUpYears: [16, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 130,
        measureOfEffect: ['HR'],
        adjustedFor: 'sex, race, age',
        effectSize: [0.89, 0.61, 1.29],
        weight: 0.25
      },
      {
        publicationYear: 2012, firstAuthor: 'Unverzagt', studyName: 'ACTIVE', country: 'US', context: ['H'],
        period: [null, null],
        studyType: ['RCT'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2786,
        baselineFemalePercentage: 76.0,
        sampleAgeMean: '74',
        baselineEducation: '13',
        usedDiagnosticCriteria: false,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 5,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 189,
        measureOfEffect: ['HR'],
        adjustedFor: 'intervention, age, sex, white, married, alcohol, MMSE, physical function, depression, diabetes, stroke or TIA',
        effectSize: [0.85, 0.72, 1.01],
        weight: 1.20
      },
      {
        publicationYear: 2013, firstAuthor: 'St John', studyName: 'MSHA', country: 'CA', context: ['H'],
        period: [1991, 1996],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1468,
        baselineFemalePercentage: 58.5,
        sampleAgeMean: '76.2 (7.1)',
        baselineEducation: '9.3 (3.6)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 96,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex, subjective memory loss, depression, functional status, MMSE, self-rated health',
        effectSize: [0.98, 0.91, 1.05],
        weight: 5.91
      },
      {
        publicationYear: 2014, firstAuthor: 'Borenstein', studyName: 'Kame', country: 'US', context: ['H'],
        period: [1992, 2001],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['Ja-Am'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 1836,
        baselineFemalePercentage: 61.8,
        sampleAgeMean: '77.1 (7.4) cases<br/>71.4 (5.4) other',
        baselineEducation: '11.7 (2.9) cases<br/>12.0 (2.9) other',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 4,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 173,
        measureOfEffect: ['HR'],
        adjustedFor: 'age',
        effectSize: [0.94, 0.87, 1.02],
        weight: 4.92
      },
      {
        publicationYear: 2015, firstAuthor: 'Contador', studyName: 'NEDICES', country: 'ES', context: ['H'],
        period: [1994, 1998],
        studyType: ['PC'],
        sampling: ['A', 'R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2711,
        baselineFemalePercentage: 56.8,
        sampleAgeMean: '72.9 (6.1)',
        baselineEducation: '6.9 (5.2)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 91,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, comorbidities, smoking, alcohol consumption',
        effectSize: [0.90, 0.85, 0.94],
        weight: 10.37
      },
      {
        publicationYear: 2016, firstAuthor: 'Then', studyName: 'LEILA75+', country: 'DE', context: ['H'],
        period: [1997, 2013],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 938,
        baselineFemalePercentage: 73.8,
        sampleAgeMean: '81.5 (4.8)',
        baselineEducation: '11.9 (1.8)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 6,
        followUpYears: [15, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 189,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, marital status, living situation, diabetes, heart attack, stroke, history of depression',
        effectSize: [0.91, 0.83, 0.99],
        weight: 4.10
      },
      {
        publicationYear: 2016, firstAuthor: 'Zahodne', studyName: 'W HAP', country: 'US', context: ['H'],
        period: [1992, 2011],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2593,
        baselineFemalePercentage: 69.0,
        sampleAgeMean: '76 (approx)',
        baselineEducation: '10 (approx)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 16,
        followUpYears: [19, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 595,
        measureOfEffect: ['OR'],
        adjustedFor: 'American, Hispanic, depression, hypertension, diabetes, stroke, APOE-e4, memory decline group',
        effectSize: [0.93, 0.91, 0.95],
        weight: 26.15
      },
      {
        publicationYear: 2018, firstAuthor: 'Hendrie', studyName: 'IIDP', country: 'US', context: ['H'],
        period: [1992, 2009],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['Af-Am'],
        sampleAgeRecruited: [70, 100],
        contributingNumber: 3276,
        baselineFemalePercentage: 65.5,
        sampleAgeMean: '77.7 (5.9) 1992 cohort<br/>77.2 (5.5) 2001 cohort',
        baselineEducation: '9.3 (3.1) 1992 cohort<br/>11.4(2.7) 2001 cohort',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 7,
        followUpYears: [17, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 285,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, rural vs urban residence, 2001 vs 1992 cohort',
        effectSize: [0.93, 0.89, 0.97],
        weight: 12.94
      },
      {
        isAverageRow: true,
        // JANET: these are fake numbers
        effectSize: [0.92, 0.91, 0.94, true], // true indicates this is an average of other values
      }

      // JANET - copy and paste EMPTY rows and enter the data
      // where there is '' it is a string; otherwise it's a number
      // [] indicates an array, so far just of numbers
      /*

      {
        publicationYear: , firstAuthor: '', studyName: '', country: '', context: [''],
        period: [, ],
        studyType: [''],
        sampling: [''],
        populationRecruited: '',
        sampleAgeRecruited: [, ],
        contributingNumber: ,
        baselineFemalePercentage: ,
        sampleAgeMean: '',
        baselineEducation: '',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUpsMin: , numFollowUpsMax: ,
        followUpYears: [, ''],
        riskOfBias: LowMedHigh.,
        numberIncidentCases: ,
        measureOfEffect: [''],
        adjustedFor: '',
        effectSize: [, , ],
        weight: ''
      }

      */
    ];
  }

  // DICHOTOMOUS
  public getDichotomousData(): any[] {
    return [
      {
        category: 'Alzheimer\'s disease',
        publicationYear: 2000, firstAuthor: 'He', studyName: 'unknown', country: 'CN', context: ['LM'],
        period: [1987, 1997],
        studyType: ['PC'],
        sampling: ['RC'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 1203,
        baselineFemalePercentage: 58,
        sampleAgeMean: 'unclear',
        baselineEducation: '19% illiteracy (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [10, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 124,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex',
        cutoff: 'illiterate'
        effectSize: [1.18, 0.61, 2.27],
        weight: 21.10
      },
      {
        publicationYear: 2008, firstAuthor: 'Lee', studyName: 'KYS', country: 'KR', context: ['H'],
        period: [1996, 2003],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 658,
        baselineFemalePercentage: 57.7,
        sampleAgeMean: '72.2 (5.6)',
        baselineEducation: '26.4% illiteracy',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [7, mean 5.4 (1.6)],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 74,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, education years',
        cutoff: 'illiterate'
        effectSize: [1.78, 1.08, 2.93],
        weight: 9.26
      },
      {
        publicationYear: 1999, firstAuthor: 'Letenneur', studyName: 'PAQUID', country: 'FR', context: ['H'],
        period: [1987, 1993],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2881,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: '4.2% no education',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 140,
        measureOfEffect: ['HR'],
        adjustedFor: 'sex, age x sex',
        cutoff: 'no education or no primary school diploma'
        effectSize: [1.78, 1.27, 2.45],
        weight: 17.62
      },
      {
        publicationYear: 1995, firstAuthor: 'Yoshitake', studyName: 'Hisayama', country: 'JP', context: ['H'],
        period: [1985, 1992],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 828,
        baselineFemalePercentage: 59.7,
        sampleAgeMean: '74 (approx)',
        baselineEducation: '26% low ed (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [7, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 103,
        measureOfEffect: ['RR'],
        adjustedFor: 'age',
        cutoff: '6 years'
        effectSize: [1.18, 0.61, 2.27],
        weight: 5.74
      },
      {
        publicationYear: 1999, firstAuthor: 'Geerlings', studyName: 'AMSTEL', country: 'NL', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2152,
        baselineFemalePercentage: 60,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, 'mean 3.2'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 77,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex',
        cutoff: '6 years'
        effectSize: [2.09, 1.29, 3.38],
        weight: 9.83
      },
      {
        publicationYear: 1992, firstAuthor: 'Beard', studyName: 'REP', country: 'US', context: ['H'],
        period: [1975, 1979],
        studyType: ['CC'],
        sampling: ['M'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [null, null, 'unclear'], // unclear
        contributingNumber: 482,
        baselineFemalePercentage: 73.9,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: null, // latter is N/A
        numFollowUps: null,
        followUpYears: [null, 'N/A'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 241,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex',
        cutoff: '9 years' // additional to continuous
        effectSize: [1.13, 0.69, 1.85],
        weight: 9.45
      },
      {
        publicationYear: 2005, firstAuthor: 'Borenstein', studyName: 'Kame', country: 'US', context: ['H'],
        period: [1992, 2001],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['JA'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1859,
        baselineFemalePercentage: 56,
        sampleAgeMean: '72 (approx)',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 4,
        followUpYears: [9, mean 6.0 (2.7)],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 90,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, gender',
        cutoff: '11 years'
        effectSize: [1.77, 1.12, 2.80],
        weight: 10.67
      },
      {
        publicationYear: 2000, firstAuthor: 'Moceri', studyName: 'unknown', country: 'US', context: ['H'],
        period: [1987, 1996],
        studyType: ['CC'],
        sampling: ['M'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [60, 100],
        contributingNumber: 770,
        baselineFemalePercentage: 63,
        sampleAgeMean: '78 (approx)',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: null,
        numFollowUps: null,
        followUpYears: [null, 'N/A'],
        riskOfBias: LowMedHigh.High,
        numberIncidentCases: 393,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, gender, siblings, APOE-e4',
        cutoff: 'less than high school'
        effectSize: [2.27, 1.67, 3.33],
        weight: 16.34
      },
      {
        isAverageRow: true,
        // JANET: these are fake numbers
        effectSize: [1.85, 1.56, 2.18, true], // true indicates this is an average of other values
      },
      {
        category: 'All dementia',
        publicationYear: 2012, firstAuthor: 'Prince', studyName: 'Unknown', country: 'CU-DO-VE-PE-MX-CN', context: ['LM'],
        period: [2003, 2010], 
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 8137,
        baselineFemalePercentage: 64, 
        sampleAgeMean: '77.1 (6.1)',
        baselineEducation: '18% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [5, 'mean 4.4'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 770,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, occupation, assets',
        cutoff: '(il)literacy'
        effectSize: [1.47, 1.19, 1.82],
        weight: 15.89
      },
      {
        publicationYear: 1999, firstAuthor: 'Letenneur', studyName: 'PAQUID', country: 'FR', context: ['H'],
        period: [1987, 1993], 
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2881,
        baselineFemalePercentage: null, 
        sampleAgeMean: 'unclear',
        baselineEducation: '4.2% no education',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 190,
        measureOfEffect: ['HR'],
        adjustedFor: 'sex, age x sex',
        cutoff: 'no education or no primary school diploma'
        effectSize: [1.82, 1.36, 2.42],
        weight: 11.29
      },
      {
        publicationYear: 1994, firstAuthor: 'Bickel', studyName: 'unknown', country: 'DE', context: ['H'],
        period: [1982, 1989],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 422,
        baselineFemalePercentage: 69, 
        sampleAgeMean: '75 approx',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: null, screenedBeforeClinicalEvaluation: false, 
        numFollowUps: 1,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 50,
        measureOfEffect: ['RR'],
        adjustedFor: 'age',
        cutoff: 'elementary school'
        effectSize: [1.48, 0.60, 3.40],
        weight: 1.86
      },
      {
        publicationYear: 1994, firstAuthor: 'Stern', studyName: 'unknown', country: 'US', context: ['H'],
        period: [null, null], 
        studyType: ['PC'],
        sampling: ['R-V'],
        populationRecruited: ['C-H'],
        sampleAgeRecruited: [65, 99],
        contributingNumber: 583,
        baselineFemalePercentage: 72.9, 
        sampleAgeMean: '74.0 (7.6)',
        baselineEducation: '44% low (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false, 
        numFollowUps: 4,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 106,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, occupation',
        cutoff: '8 years'
        effectSize: [2.02, 1.33, 3.06],
        weight: 6.70
      },
      {
        publicationYear: 2001, firstAuthor: 'Scarmeas', studyName: 'unknown', country: 'US', context: ['H'],
        period: [1991, 1998], 
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1772,
        baselineFemalePercentage: 68, 
        sampleAgeMean: '76 (approx)',
        baselineEducation: '49% high (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false, 
        numFollowUps: 3,
        followUpYears: [7, 'mean 2.9'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 207,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, ethnic group, occupation, leisure activities',
        cutoff: '8 years'
        effectSize: [1.23, 0.89, 1.72],
        weight: 9.48
      },
      {
        publicationYear: 2014, firstAuthor: 'Kaup', studyName: 'Health ABC', country: 'US', context: ['H'],
        period: [1997, 2009], 
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [70, 79],
        contributingNumber: 2458,
        baselineFemalePercentage: 52,
        sampleAgeMean: '76 (approx),
        baselineEducation: '23.3% limited literacy',
        usedDiagnosticCriteria: null, screenedBeforeClinicalEvaluation: null,
        numFollowUps: 5,
        followUpYears: [9, mean 7.3 (1.9)],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 496,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, race, education, household income, hypertensio, myocardial infarction, stroke/TIA, obesity, smoking, alcohol, APOE-e4',
        cutoff: '9th grade reading level'
        effectSize: [1.39, 1.04, 1.85],
        weight: 11.30
      },
      {
        publicationYear: 2016, firstAuthor: 'Then', studyName: 'LEILA75+', country: 'DE', context: ['H'],
        period: [1997, 2013], 
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 938,
        baselineFemalePercentage: 73.8,
        sampleAgeMean: '81.5 (4.8)',
        baselineEducation: '11.9 (1.8)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false, 
        numFollowUps: 6,
        followUpYears: [15, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 189,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, martial status, living situation, diabetes, heart attack, stroke, history of depression',
        cutoff: '10 years'
        effectSize: [1.47, 1.06, 2.04],
        weight: 9.61
      },
      {
        publicationYear: 2019, firstAuthor: 'Kotaki', studyName: 'Ohsaki', country: 'JP', context: ['H'],
        period: [2006, 2012], 
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 8563,
        baselineFemalePercentage: 49.6, 
        sampleAgeMean: '73.1 (5.6)',
        baselineEducation: '26.7% low ed',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: false, // former is unclear
        numFollowUps: 5,
        followUpYears: [6, mean 5.7],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 577,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, diabetes, hypertension, BMI, exercise, psychological distress, smoking',
        cutoff: 'finished school < age 16'
        effectSize: [1.17, 0.99, 1.39],
        weight: 19.16
      },
      {
        isAverageRow: true,
        // JANET: these are fake numbers
        effectSize: [1.48, 1.31, 1.67, true], // true indicates this is an average of other values
      }
    ];
  }

  // CATEGORICAL
  public getCategoricalData(): any[] {
    return [
      {
        category: 'Alzheimer\'s disease',
        publicationYear: 2008, firstAuthor: 'Bermejo-Pareja', studyName: 'NEDICES', country: 'ES', context: ['H'],
        period: [1994, 1998],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 3891,
        baselineFemalePercentage: 57, // approx
        sampleAgeMean: '79.5 (6.8)',
        baselineEducation: 'Cases 30.4% illiterate<br/>controls 11.3% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [3.2, 'Mean (0.03 - 6.6)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 161,
        measureOfEffect: ['HR'],
        adjustedFor: 'Age, sex, current smoker, current ethanol consumption, stroke, diabetes mellitus, hypertension, heart disease, depressive symptoms',
        effectSize: [4.8, 1.98, 11.61],
        educationSubcategory: 'Illiterate', // additional to others
        referenceSubcategory: 'Secondary or higher studies' // additional to others
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.11, 0.88, 5],
        educationSubcategory: 'Can read and write',
        referenceSubcategory: 'Secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.73, 0.7, 4.29],
        educationSubcategory: 'Primary studies',
        referenceSubcategory: 'Secondary or higher studies'
      },
      {
        publicationYear: 2002, firstAuthor: 'Di Carlo', studyName: 'ILSA', country: 'IT', context: ['H'],
        period: [1992, 1995],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2498,
        baselineFemalePercentage: 47,
        sampleAgeMean: '74 (5.6)',
        baselineEducation: '6.1 mean (4.6)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [3.8, 'Mean (1.09)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 127,
        measureOfEffect: ['HR'],
        adjustedFor: 'Multivariate model, covariates not specified but age and "demograp H variables"',
        effectSize: [0.32, 0.12, 0.89],
        educationSubcategory: '6-10 years',
        referenceSubcategory: '0-5 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.34, 0.12, 0.96],
        educationSubcategory: '>= 11 years',
        referenceSubcategory: '0-5 years'
      },
    ];
  }
}
 // CATEGORICAL
  public getCategoricalData(): any[] {
    return [
      {
        category: 'Alzheimer\'s disease',
        publicationYear: 2008, firstAuthor: 'Bermejo-Pareja', studyName: 'NEDICES', country: 'ES', context: 'HIC',
        period: [1994, 1998],
        studyType: 'PC',
        sampling: 'All',
        populationRecruited: 'Non-specific',
        sampleAgeRecruited: [65, 100],
        contributingNumber: 3891,
        baselineFemalePercentage: 57, // approx
        sampleAgeMean: '79.5 (6.8)',
        baselineEducation: 'Cases 30.4% illiterate<br/>controls 11.3% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUpsMin: 1, numFollowUpsMax: 1,
        followUpYears: [3.2, 'Mean (0.03 - 6.6)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 161,
        measureOfEffect: 'HR',
        adjustedFor: 'Age, sex, current smoker, current ethanol consumption, stroke, diabetes mellitus, hypertension, heart disease, depressive symptoms',
        effectSize: [4.8, 1.98, 11.61],
        educationSubcategory: 'Illiterate', // additional to others
        referenceSubcategory: 'Secondary or higher studies' // additional to others
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.11, 0.88, 5],
        educationSubcategory: 'Can read and write',
        referenceSubcategory: 'Secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.73, 0.7, 4.29],
        educationSubcategory: 'Primary studies',
        referenceSubcategory: 'Secondary or higher studies'
      },
      {
        publicationYear: 2002, firstAuthor: 'Di Carlo', studyName: 'ILSA', country: 'IT', context: 'HIC',
        period: [1992, 1995],
        studyType: 'PC',
        sampling: 'Random',
        populationRecruited: 'Non-specific',
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2498,
        baselineFemalePercentage: 47,
        sampleAgeMean: '74 (5.6)',
        baselineEducation: '6.1 mean (4.6)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUpsMin: 1, numFollowUpsMax: 1,
        followUpYears: [3.8, 'Mean (1.09)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 127,
        measureOfEffect: 'HR',
        adjustedFor: 'Multivariate model, covariates not specified but age and "demographic variables"',
        effectSize: [0.32, 0.12, 0.89],
        educationSubcategory: '6-10 years',
        referenceSubcategory: '0-5 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.34, 0.12, 0.96],
        educationSubcategory: '>= 11 years',
        referenceSubcategory: '0-5 years'
      },
    ];
  }
}
