import { Injectable } from '@angular/core';
import { LowMedHigh } from './enums';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor() { }

  // CONTINUOUS
  public getContinuousData(): any[] {
    return [
      {
        category: 'Alzheimer\'s disease',
        publicationYear: 1997, firstAuthor: 'Evans', studyName: 'Unknown', country: 'US', context: ['H'],
        period: [1982, 1987],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 642,
        baselineFemalePercentage: 56.4,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [4.3, 'average 4.3'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 95,
        measureOfEffect: ['OR'],
        adjustedFor: 'follow-up interval, age, sex, occupation, income',
        effectSize: [0.85, 0.75, 0.95],
        weight: 8.01
      },
      {
        publicationYear: 2001, firstAuthor: 'Tyas', studyName: 'MSHA', country: 'CA', context: ['H'],
        period: [1991, 1997],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 694,
        baselineFemalePercentage: 62.4,
        sampleAgeMean: '74.0 (5.8)',
        baselineEducation: '10.6 (3.2)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 36,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex',
        effectSize: [0.86, 0.76, 0.96],
        weight: 8.14
      },
      {
        publicationYear: 2002, firstAuthor: 'Kukull', studyName: 'ACT', country: 'US', context: ['H'],
        period: [1994, 2000],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2356,
        baselineFemalePercentage: 59.0,
        sampleAgeMean: '79.4 w/ dementia<br/>74.0 w/o dementia',
        baselineEducation: '12.8 w/ dementia<br/>13.9 w/o dementia',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'presume 4'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 151,
        measureOfEffect: ['RaR'],
        adjustedFor: 'age, sex, APOE',
        effectSize: [0.91, 0.86, 0.97],
        weight: 16.1
      },
      {
        publicationYear: 2002, firstAuthor: 'Lindsay', studyName: 'CSHA', country: 'CA', context: ['H'],
        period: [1992, 1996],
        studyType: ['CC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 4088,
        baselineFemalePercentage: 58.0,
        sampleAgeMean: '81.0 cases<br/>72.9 controls',
        baselineEducation: '9.9 cases<br/>11.1 controls',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 194,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex, education',
        effectSize: [0.92, 0.88, 0.97],
        weight: 18.35
      },
      {
        publicationYear: 2008, firstAuthor: 'Lee', studyName: 'KYS', country: 'KR', context: ['H'],
        period: [1996, 2003],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 658,
        baselineFemalePercentage: 57.7,
        sampleAgeMean: '72.2 (5.6)',
        baselineEducation: '2.5 (3.5)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [5.4, '5.4 (1.6)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 74,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, literacy',
        effectSize: [0.85, 0.74, 0.98],
        weight: 6.26
      },
      {
        publicationYear: 2014, firstAuthor: 'Borenstein', studyName: 'Kame', country: 'US', context: ['H'],
        period: [1992, 2001],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['Ja-Am'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 1836,
        baselineFemalePercentage: 61.8,
        sampleAgeMean: '77.1 (7.4) cases<br/>71.4 (5.4) other',
        baselineEducation: '11.7 (2.9) cases<br/>13.0 (2.9) other',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 4,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 135,
        measureOfEffect: ['HR'],
        adjustedFor: 'age',
        effectSize: [0.92, 0.84, 1.01],
        weight: 10.91
      },
      {
        publicationYear: 2017, firstAuthor: 'Yu', studyName: 'MAP', country: 'US', context: ['H'],
        period: [1997, 2004],
        studyType: ['PC'],
        sampling: ['V'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [58.8, 100.2],
        contributingNumber: 805,
        baselineFemalePercentage: 76.7,
        sampleAgeMean: '81.5 (7.7)',
        baselineEducation: '15.3 (3.0)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 8,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 102,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, total literacy',
        effectSize: [1.04, 0.97, 1.12],
        weight: 13.99
      },
      {
        publicationYear: 2018, firstAuthor: 'Hendrie', studyName: 'IIDP', country: 'US', context: ['H'],
        period: [1992, 2009],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['Af-Am'],
        sampleAgeRecruited: [70, 100],
        contributingNumber: 3276,
        baselineFemalePercentage: 65.5,
        sampleAgeMean: '77.7 (5.9) 1992 cohort<br/>77.2 (5.5) 2001 cohort',
        baselineEducation: '9.3 (3.1) 1992 cohort<br/>11.4(2.7) 2001 cohort',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 7,
        followUpYears: [17, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 233,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, rural vs urban residence, 2001 vs 1992 cohort',
        effectSize: [0.91, 0.87, 0.96],
        weight: 18.24
      },
      {
        isAverageRow: true,
        effectSize: [0.92, 0.88, 0.95, true], // true indicates this is an average of other values
      },
      {
        category: 'All dementia',
        publicationYear: 1994, firstAuthor: 'Stern', studyName: 'Unknown', country: 'US', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['V', 'mixed'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [60, 99],
        contributingNumber: 583,
        baselineFemalePercentage: 72.9,
        sampleAgeMean: '74.0 (7.6)',
        baselineEducation: '9.6 (4.7)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 4,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 106,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender',
        effectSize: [0.92, 0.88, 0.95],
        weight: 15.06
      },
      {
        publicationYear: 1997, firstAuthor: 'Schmand - A', studyName: 'AMSTEL', country: 'NL', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2063,
        baselineFemalePercentage: 62.6,
        sampleAgeMean: '74.1 (5.5) normal <br/>77.5 cases (5.0)',
        baselineEducation: '9.1 (3.0) normal <br/>8.0 (1.8) cases',
        usedDiagnosticCriteria: false,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 152,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, gender, pre-morbid intelligence, occupation, comorbidity, family history',
        effectSize: [0.86, 0.57, 1.31],
        weight: 0.20
      },
      {
        publicationYear: 2002, firstAuthor: 'Kukull', studyName: 'ACT', country: 'US', context: ['H'],
        period: [1994, 2000],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2356,
        baselineFemalePercentage: 59.0,
        sampleAgeMean: '79.4 w/ dementia<br/>74.0 w/o dementia',
        baselineEducation: '12.8 w/ dementia<br/>13.9 w/o dementia',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'presume 4'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 215,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex, APOE',
        effectSize: [0.94, 0.90, 0.99],
        weight: 11.23
      },
      {
        publicationYear: 2010, firstAuthor: 'Kerola', studyName: 'Kuopio 75+', country: 'FI', context: ['H'],
        period: [1998, 2003],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 303,
        baselineFemalePercentage: 72.0,
        sampleAgeMean: '80 (approx)',
        baselineEducation: '7 (approx)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 59,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, hypertension, B-type natriuretic peptide',
        effectSize: [0.50, 0.33, 0.77],
        weight: 0.20
      },
      {
        publicationYear: 2010, firstAuthor: 'Brayne', studyName: 'EClipSE - CFAS, CC75C, Vantaa 85+', country: 'FI-GB', context: ['H'],
        period: [1985, 2005],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 872,
        baselineFemalePercentage: 68.0,
        sampleAgeMean: '90 (68-107)',
        baselineEducation: 'median 9 (range 0-24)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 7,
        followUpYears: [20, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 486,
        measureOfEffect: ['OR'],
        adjustedFor: 'age at death, sex, study',
        effectSize: [0.89, 0.83, 0.94],
        weight: 7.46
      },
      {
        publicationYear: 2012, firstAuthor: 'Katz', studyName: 'EAS', country: 'US', context: ['H'],
        period: [1993, 2009],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [70, 100],
        contributingNumber: 1168,
        baselineFemalePercentage: 60.7,
        sampleAgeMean: '78.8 (5.42)',
        baselineEducation: '13.5 (3.50)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 16,
        followUpYears: [16, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 130,
        measureOfEffect: ['HR'],
        adjustedFor: 'sex, race, age',
        effectSize: [0.89, 0.61, 1.29],
        weight: 0.25
      },
      {
        publicationYear: 2012, firstAuthor: 'Unverzagt', studyName: 'ACTIVE', country: 'US', context: ['H'],
        period: [null, null],
        studyType: ['RCT'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2786,
        baselineFemalePercentage: 76.0,
        sampleAgeMean: '74',
        baselineEducation: '13',
        usedDiagnosticCriteria: false,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 5,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 189,
        measureOfEffect: ['HR'],
        adjustedFor: 'intervention, age, sex, white, married, alcohol, MMSE, physical function, depression, diabetes, stroke or TIA',
        effectSize: [0.85, 0.72, 1.01],
        weight: 1.20
      },
      {
        publicationYear: 2013, firstAuthor: 'St John', studyName: 'MSHA', country: 'CA', context: ['H'],
        period: [1991, 1996],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1468,
        baselineFemalePercentage: 58.5,
        sampleAgeMean: '76.2 (7.1)',
        baselineEducation: '9.3 (3.6)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 96,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex, subjective memory loss, depression, functional status, MMSE, self-rated health',
        effectSize: [0.98, 0.91, 1.05],
        weight: 5.91
      },
      {
        publicationYear: 2014, firstAuthor: 'Borenstein', studyName: 'Kame', country: 'US', context: ['H'],
        period: [1992, 2001],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['Ja-Am'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 1836,
        baselineFemalePercentage: 61.8,
        sampleAgeMean: '77.1 (7.4) cases<br/>71.4 (5.4) other',
        baselineEducation: '11.7 (2.9) cases<br/>12.0 (2.9) other',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 4,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 173,
        measureOfEffect: ['HR'],
        adjustedFor: 'age',
        effectSize: [0.94, 0.87, 1.02],
        weight: 4.92
      },
      {
        publicationYear: 2015, firstAuthor: 'Contador', studyName: 'NEDICES', country: 'ES', context: ['H'],
        period: [1994, 1998],
        studyType: ['PC'],
        sampling: ['A', 'R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2711,
        baselineFemalePercentage: 56.8,
        sampleAgeMean: '72.9 (6.1)',
        baselineEducation: '6.9 (5.2)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 91,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, comorbidities, smoking, alcohol consumption',
        effectSize: [0.90, 0.85, 0.94],
        weight: 10.37
      },
      {
        publicationYear: 2016, firstAuthor: 'Then', studyName: 'LEILA75+', country: 'DE', context: ['H'],
        period: [1997, 2013],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 938,
        baselineFemalePercentage: 73.8,
        sampleAgeMean: '81.5 (4.8)',
        baselineEducation: '11.9 (1.8)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 6,
        followUpYears: [15, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 189,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, marital status, living situation, diabetes, heart attack, stroke, history of depression',
        effectSize: [0.91, 0.83, 0.99],
        weight: 4.10
      },
      {
        publicationYear: 2016, firstAuthor: 'Zahodne', studyName: 'W HAP', country: 'US', context: ['H'],
        period: [1992, 2011],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2593,
        baselineFemalePercentage: 69.0,
        sampleAgeMean: '76 (approx)',
        baselineEducation: '10 (approx)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 16,
        followUpYears: [19, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 595,
        measureOfEffect: ['OR'],
        adjustedFor: 'American, Hispanic, depression, hypertension, diabetes, stroke, APOE-e4, memory decline group',
        effectSize: [0.93, 0.91, 0.95],
        weight: 26.15
      },
      {
        publicationYear: 2018, firstAuthor: 'Hendrie', studyName: 'IIDP', country: 'US', context: ['H'],
        period: [1992, 2009],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['Af-Am'],
        sampleAgeRecruited: [70, 100],
        contributingNumber: 3276,
        baselineFemalePercentage: 65.5,
        sampleAgeMean: '77.7 (5.9) 1992 cohort<br/>77.2 (5.5) 2001 cohort',
        baselineEducation: '9.3 (3.1) 1992 cohort<br/>11.4(2.7) 2001 cohort',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 7,
        followUpYears: [17, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 285,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, rural vs urban residence, 2001 vs 1992 cohort',
        effectSize: [0.93, 0.89, 0.97],
        weight: 12.94
      },
      {
        isAverageRow: true,
        effectSize: [0.92, 0.91, 0.94, true], // true indicates this is an average of other values
      }
    ];
  }

  // DICHOTOMOUS
  public getDichotomousData(): any[] {
    return [
      {
        category: 'Alzheimer\'s disease',
        publicationYear: 2000, firstAuthor: 'He', studyName: 'unknown', country: 'CN', context: ['LM'],
        period: [1987, 1997],
        studyType: ['PC'],
        sampling: ['RC'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 1203,
        baselineFemalePercentage: 58,
        sampleAgeMean: 'unclear',
        baselineEducation: '19% illiteracy (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [10, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 124,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex',
        cutoff: 'illiterate',
        effectSize: [1.18, 0.61, 2.27],
        weight: 21.10
      },
      {
        publicationYear: 2008, firstAuthor: 'Lee', studyName: 'KYS', country: 'KR', context: ['H'],
        period: [1996, 2003],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 658,
        baselineFemalePercentage: 57.7,
        sampleAgeMean: '72.2 (5.6)',
        baselineEducation: '26.4% illiteracy',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [7, 'mean 5.4 (1.6)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 74,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, education years',
        cutoff: 'illiterate',
        effectSize: [1.78, 1.08, 2.93],
        weight: 9.26
      },
      {
        publicationYear: 1999, firstAuthor: 'Letenneur', studyName: 'PAQUID', country: 'FR', context: ['H'],
        period: [1987, 1993],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2881,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: '4.2% no education',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 140,
        measureOfEffect: ['HR'],
        adjustedFor: 'sex, age x sex',
        cutoff: 'no education or<br/>no primary<br/>school diploma',
        effectSize: [1.78, 1.27, 2.45],
        weight: 17.62
      },
      {
        publicationYear: 1995, firstAuthor: 'Yoshitake', studyName: 'Hisayama', country: 'JP', context: ['H'],
        period: [1985, 1992],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 828,
        baselineFemalePercentage: 59.7,
        sampleAgeMean: '74 (approx)',
        baselineEducation: '26% low ed (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [7, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 103,
        measureOfEffect: ['RR'],
        adjustedFor: 'age',
        cutoff: '6 years',
        effectSize: [1.18, 0.61, 2.27],
        weight: 5.74
      },
      {
        publicationYear: 1999, firstAuthor: 'Geerlings', studyName: 'AMSTEL', country: 'NL', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2152,
        baselineFemalePercentage: 60,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, 'mean 3.2'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 77,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex',
        cutoff: '6 years',
        effectSize: [2.09, 1.29, 3.38],
        weight: 9.83
      },
      {
        publicationYear: 1992, firstAuthor: 'Beard', studyName: 'REP', country: 'US', context: ['H'],
        period: [1975, 1979],
        studyType: ['CC'],
        sampling: ['M'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [null, null, 'unclear'], // unclear
        contributingNumber: 482,
        baselineFemalePercentage: 73.9,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: null, // latter is N/A
        numFollowUps: null,
        followUpYears: [null, 'N/A'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 241,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex',
        cutoff: '9 years',
        effectSize: [1.13, 0.69, 1.85],
        weight: 9.45
      },
      {
        publicationYear: 2005, firstAuthor: 'Borenstein', studyName: 'Kame', country: 'US', context: ['H'],
        period: [1992, 2001],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['JA'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1859,
        baselineFemalePercentage: 56,
        sampleAgeMean: '72 (approx)',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 4,
        followUpYears: [9, 'mean 6.0 (2.7)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 90,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, gender',
        cutoff: '11 years',
        effectSize: [1.77, 1.12, 2.80],
        weight: 10.67
      },
      {
        publicationYear: 2000, firstAuthor: 'Moceri', studyName: 'unknown', country: 'US', context: ['H'],
        period: [1987, 1996],
        studyType: ['CC'],
        sampling: ['M'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [60, 100],
        contributingNumber: 770,
        baselineFemalePercentage: 63,
        sampleAgeMean: '78 (approx)',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: null,
        numFollowUps: null,
        followUpYears: [null, 'N/A'],
        riskOfBias: LowMedHigh.High,
        numberIncidentCases: 393,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, gender, siblings, APOE-e4',
        cutoff: 'less than high school',
        effectSize: [2.27, 1.67, 3.33],
        weight: 16.34
      },
      {
        isAverageRow: true,
        effectSize: [1.85, 1.56, 2.18, true], // true indicates this is an average of other values
      },
      {
        category: 'All dementia',
        publicationYear: 2012, firstAuthor: 'Prince', studyName: 'Unknown', country: 'CU-DO-VE-PE-MX-CN', context: ['LM'],
        period: [2003, 2010],
        studyType: ['PC'],
        sampling: ['?'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 8137,
        baselineFemalePercentage: 64,
        sampleAgeMean: '77.1 (6.1)',
        baselineEducation: '18% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [5, 'mean 4.4'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 770,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, occupation, assets',
        cutoff: '(il)literacy',
        effectSize: [1.47, 1.19, 1.82],
        weight: 15.89
      },
      {
        publicationYear: 1999, firstAuthor: 'Letenneur', studyName: 'PAQUID', country: 'FR', context: ['H'],
        period: [1987, 1993],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2881,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: '4.2% no education',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 190,
        measureOfEffect: ['HR'],
        adjustedFor: 'sex, age x sex',
        cutoff: 'no education or<br/>no primary<br/>school diploma',
        effectSize: [1.82, 1.36, 2.42],
        weight: 11.29
      },
      {
        publicationYear: 1994, firstAuthor: 'Bickel', studyName: 'unknown', country: 'DE', context: ['H'],
        period: [1982, 1989],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 422,
        baselineFemalePercentage: 69,
        sampleAgeMean: '75 approx',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: null, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [8, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 50,
        measureOfEffect: ['RR'],
        adjustedFor: 'age',
        cutoff: 'elementary school',
        effectSize: [1.48, 0.60, 3.40],
        weight: 1.86
      },
      {
        publicationYear: 1994, firstAuthor: 'Stern', studyName: 'unknown', country: 'US', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['R', 'V'],
        populationRecruited: ['C', 'H'],
        sampleAgeRecruited: [65, 99],
        contributingNumber: 583,
        baselineFemalePercentage: 72.9,
        sampleAgeMean: '74.0 (7.6)',
        baselineEducation: '44% low (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 4,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 106,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, occupation',
        cutoff: '8 years',
        effectSize: [2.02, 1.33, 3.06],
        weight: 6.70
      },
      {
        publicationYear: 2001, firstAuthor: 'Scarmeas', studyName: 'unknown', country: 'US', context: ['H'],
        period: [1991, 1998],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1772,
        baselineFemalePercentage: 68,
        sampleAgeMean: '76 (approx)',
        baselineEducation: '49% high (approx)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 3,
        followUpYears: [7, 'mean 2.9'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 207,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, ethnic group, occupation, leisure activities',
        cutoff: '8 years',
        effectSize: [1.23, 0.89, 1.72],
        weight: 9.48
      },
      {
        publicationYear: 2014, firstAuthor: 'Kaup', studyName: 'Health ABC', country: 'US', context: ['H'],
        period: [1997, 2009],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [70, 79],
        contributingNumber: 2458,
        baselineFemalePercentage: 52,
        sampleAgeMean: '76 (approx)',
        baselineEducation: '23.3% limited literacy',
        usedDiagnosticCriteria: null, screenedBeforeClinicalEvaluation: null,
        numFollowUps: 5,
        followUpYears: [9, 'mean 7.3 (1.9)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 496,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, race, education, household income, hypertensio, myocardial infarction, stroke/TIA, obesity, smoking, alcohol, APOE-e4',
        cutoff: '9th grade<br/>reading level',
        effectSize: [1.39, 1.04, 1.85],
        weight: 11.30
      },
      {
        publicationYear: 2016, firstAuthor: 'Then', studyName: 'LEILA75+', country: 'DE', context: ['H'],
        period: [1997, 2013],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 938,
        baselineFemalePercentage: 73.8,
        sampleAgeMean: '81.5 (4.8)',
        baselineEducation: '11.9 (1.8)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 6,
        followUpYears: [15, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 189,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, martial status, living situation, diabetes, heart attack, stroke, history of depression',
        cutoff: '10 years',
        effectSize: [1.47, 1.06, 2.04],
        weight: 9.61
      },
      {
        publicationYear: 2019, firstAuthor: 'Kotaki', studyName: 'Ohsaki', country: 'JP', context: ['H'],
        period: [2006, 2012],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 8563,
        baselineFemalePercentage: 49.6,
        sampleAgeMean: '73.1 (5.6)',
        baselineEducation: '26.7% low ed',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: false, // former is unclear
        numFollowUps: 5,
        followUpYears: [6, 'mean 5.7'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 577,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, diabetes, hypertension, BMI, exercise, psychological distress, smoking',
        cutoff: 'finished school<br/>< age 16',
        effectSize: [1.17, 0.99, 1.39],
        weight: 19.16
      },
      {
        isAverageRow: true,
        effectSize: [1.48, 1.31, 1.67, true], // true indicates this is an average of other values
      }
    ];
  }

  // ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  public getCategoricalDataAlzheimers(): any[] {
    return [
      {
        // first category - low ed as base
        category: 'Low education base',
        publicationYear: 2003, firstAuthor: 'Harmanci', studyName: 'TAPS', country: 'TR', context: ['UM'],
        period: [null, null],
        studyType: ['CC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [70, 100],
        contributingNumber: 184,
        baselineFemalePercentage: 65.2,
        sampleAgeMean: '77.3 (6.0) cases<br>76.1 (5.8) controls',
        baselineEducation: '25% no schooling',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: null,
        followUpYears: [null, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 57,
        measureOfEffect: ['OR'],
        adjustedFor: 'unclear',
        effectSize: [0.9, 0.38, 2.12],
        educationSubcategory: 'primary education',
        referenceSubcategory: 'no schooling'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.23, 0.23, 1.37],
        educationSubcategory: 'secondary education',
        referenceSubcategory: 'no schooling'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.10, 0.02, 0.50],
        educationSubcategory: 'higher education',
        referenceSubcategory: 'no schooling'
      },
      {
        publicationYear: 2016, firstAuthor: 'Yuan', studyName: 'unknown', country: 'CN', context: ['LM'],
        period: [1997, 2002],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 12881,
        baselineFemalePercentage: 53.4,
        sampleAgeMean: 'unclear',
        baselineEducation: '34.9% 1-6 years',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'mean 3.1 (range 2.9 - 3.5)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 197,
        measureOfEffect: ['HR'],
        adjustedFor: 'age group, gender, residence status, region east vs west',
        effectSize: [0.77, 0.54, 1.12],
        educationSubcategory: '1-6 years',
        referenceSubcategory: '<1 year'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.35, 0.18, 0.66],
        educationSubcategory: '7-12 years',
        referenceSubcategory: '<1 year'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.55, 0.24, 1.26],
        educationSubcategory: '12+ years',
        referenceSubcategory: '<1 year'
      },
      {
        publicationYear: 2002, firstAuthor: 'Di Carlo', studyName: 'ILSA', country: 'IT', context: ['H'],
        period: [1992, 1995],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2498,
        baselineFemalePercentage: 47.0,
        sampleAgeMean: '74.0 (5.6)',
        baselineEducation: '6.1 (4.6)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, 'mean 3.8 (0.9)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 67,
        measureOfEffect: ['HR'],
        adjustedFor: 'age and "demographic variables"',
        effectSize: [0.32, 0.12, 0.89],
        educationSubcategory: '6-10 years',
        referenceSubcategory: '0-5 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.34, 0.12, 0.96],
        educationSubcategory: '>=11 years',
        referenceSubcategory: '<0-5 years'
      },
      {
        publicationYear: 2007, firstAuthor: 'van Oijen', studyName: 'Rotterdam', country: 'NL', context: ['H'],
        period: [1990, 2004],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 6927,
        baselineFemalePercentage: 60.0,
        sampleAgeMean: '69.5 (9.1)',
        baselineEducation: '24.1% low',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [9, null],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 568,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, BMI, ever smoking, diabetes, APOE-e4, CVD',
        effectSize: [0.82, 0.63, 1.07],
        educationSubcategory: 'low-intermediate',
        referenceSubcategory: 'low'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.72, 0.54, 0.95],
        educationSubcategory: 'high-intermediate',
        referenceSubcategory: 'low'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.56, 0.31, 0.99],
        educationSubcategory: 'high',
        referenceSubcategory: 'low'
      },
      {
        publicationYear: 2011, firstAuthor: 'Kukull', studyName: 'ACT', country: 'US', context: ['H'],
        period: [1994, 2000],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2356,
        baselineFemalePercentage: 59.0,
        sampleAgeMean: '79.4 with dementia<br>74.0 without dementia',
        baselineEducation: '7.8% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 151,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex, APOE-e4',
        effectSize: [0.73, 0.47, 1.14],
        educationSubcategory: '12-15 years',
        referenceSubcategory: '<12 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.48, 0.27, 0.84],
        educationSubcategory: '>15 years',
        referenceSubcategory: '<12 years'
      },
      // new section - high ed as base
      {
        category: 'High education base',
        publicationYear: 2005, firstAuthor: 'Ravaglia', studyName: 'CSBA', country: 'IT', context: ['H'],
        period: [1991, 2004],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 857,
        baselineFemalePercentage: 53.7,
        sampleAgeMean: '74 (6)',
        baselineEducation: '4.7 (2.4)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, '3.8 (0.8)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 72,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex',
        effectSize: [2.66, 1.02, 6.89],
        educationSubcategory: '<=3 years',
        referenceSubcategory: '6+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.20, 0.46, 3.13],
        educationSubcategory: '4-5 years',
        referenceSubcategory: '6+ years'
      },
      {
        publicationYear: 2011, firstAuthor: 'Lobo', studyName: 'Zarademp', country: 'ES', context: ['H'],
        period: [1994, 1999],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 2403,
        baselineFemalePercentage: 54.9,
        sampleAgeMean: '72.1 (9.1)',
        baselineEducation: '7.8% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, '4.5'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 87,
        measureOfEffect: ['IRR'],
        adjustedFor: 'age',
        effectSize: [3.33, 1.88, 5.67],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'primary'
      },
      {
        isSubcategoryRow: true,
        effectSize: [3.92, 1.81, 8.86],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'medium/high'
      },
      {
        publicationYear: 2008, firstAuthor: 'Bermejo-Pareja', studyName: 'NEDICES', country: 'ES', context: ['H'],
        period: [1994, 1998],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 3891,
        baselineFemalePercentage: 57,
        sampleAgeMean: '79.5 (6.8)',
        baselineEducation: '30.4% illiterate cases<br/> 11.3% illiterate controls',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [6, 'mean 3.2 (range 0.03 - 6.6)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 115,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, current smoker, current ethanol consumption, stroke, diabetes mellitus, hypertension, heart disease, depressive symptoms',
        effectSize: [4.80, 1.98, 11.61],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.11, 0.88, 5.00],
        educationSubcategory: 'can read and write',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.73, 0.70, 4.29],
        educationSubcategory: 'primary studies',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        publicationYear: 2000, firstAuthor: 'Letenneur', studyName: 'EURODEM', country: 'DK-FR-NL-GB', context: ['H'],
        period: [1988, 1996],
        studyType: ['PC'],
        sampling: ['A', 'R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 12647,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: '37.6% low',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [3, '2.24 (0.73)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 328,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, age x age, study, sex, history of MI, stroke, smoking',
        effectSize: [1.96, 1.09, 3.52],
        educationSubcategory: '<=7 years',
        referenceSubcategory: '>=12 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.42, 0.80, 2.50],
        educationSubcategory: '8-11 years',
        referenceSubcategory: '>= 12 years'
      },
      {
        publicationYear: 2007, firstAuthor: 'McDowell', studyName: 'CSHA', country: 'CA', context: ['H'],
        period: [1991, 2001],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 5177,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [10, null],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 532,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex, marital status, income, occupational attainment, health problems, exercise, alcohol, smoking',
        effectSize: [2.30, 1.58, 3.29],
        educationSubcategory: '<6 years',
        referenceSubcategory: '13+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.60, 1.19, 2.23],
        educationSubcategory: '6-8 years',
        referenceSubcategory: '13+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.30, 1.01, 1.74],
        educationSubcategory: '9-12 years',
        referenceSubcategory: '13+ years'
      }
    ];
  }

  // ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  public getCategoricalDataAllDementia(): any[] {
    return [
      {
        // category: 'All dementia',
        // first section - low ed is base
        category: 'Low education base',
        publicationYear: 2016, firstAuthor: 'Yuan', studyName: 'unknown', country: 'CN', context: ['LM'],
        period: [1997, 2002],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 12881,
        baselineFemalePercentage: 53.4,
        sampleAgeMean: 'unclear',
        baselineEducation: '34.9% 1-6 years',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'mean 3.1 (range 2.9 - 3.5)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 311,
        measureOfEffect: ['HR'],
        adjustedFor: 'age group, gender, residence status, region east vs west',
        effectSize: [0.69, 0.51, 0.92],
        educationSubcategory: '1-6 years',
        referenceSubcategory: '<1 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.34, 0.21, 0.56],
        educationSubcategory: '7-12 years',
        referenceSubcategory: '<1 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.40, 0.20, 0.78],
        educationSubcategory: '13+ years',
        referenceSubcategory: '<1 years'
      },
      {
        publicationYear: 2002, firstAuthor: 'Di Carlo', studyName: 'ILSA', country: 'IT', context: ['H'],
        period: [1992, 1995],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2498,
        baselineFemalePercentage: 47.0,
        sampleAgeMean: '74.0 (5.6)',
        baselineEducation: '6.1 (4.6)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, 'mean 3.8 (0.9)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 127,
        measureOfEffect: ['HR'],
        adjustedFor: 'age and "demographic variables"',
        effectSize: [0.39, 0.20, 0.77],
        educationSubcategory: '6-10 years',
        referenceSubcategory: '0-5 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.44, 0.23, 0.85],
        educationSubcategory: '>=11 years',
        referenceSubcategory: '0-5 years'
      },
      {
        publicationYear: 2011, firstAuthor: 'Valenzuela', studyName: 'CFAS', country: 'GB', context: ['H'],
        period: [1991, 2002],
        studyType: ['CC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 'unclear',
        baselineFemalePercentage: 60.0,
        sampleAgeMean: 'unclear',
        baselineEducation: 'median 9 (IQR 9-10)',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [10, 'mean 4.1'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 361,
        measureOfEffect: ['OR'],
        adjustedFor: 'vascular risk factors, occupation, social engagement',
        effectSize: [1.1, 0.7, 1.9],
        educationSubcategory: 'medium',
        referenceSubcategory: 'low'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.8, 0.4, 1.3],
        educationSubcategory: 'high',
        referenceSubcategory: 'low'
      },
      {
        publicationYear: 2016, firstAuthor: 'Then', studyName: 'LEILA75+', country: 'DE', context: ['H'],
        period: [1997, 2013],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 938,
        baselineFemalePercentage: 73.8,
        sampleAgeMean: '81.5 (4.8)',
        baselineEducation: '11.9 (1.8)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 6,
        followUpYears: [15, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 189,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, marital status, living situation, diabetes, heart attack, stroke, history of depression',
        effectSize: [0.95, 0.66, 1.04],
        educationSubcategory: 'CASMIN middle',
        referenceSubcategory: 'CASMIN low'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.03, 0.60, 1.77],
        educationSubcategory: 'CASMIN high',
        referenceSubcategory: 'CASMIN low'
      },
      {
        publicationYear: 2016, firstAuthor: 'Dekhtyar', studyName: 'Kungsholmen', country: 'SE', context: ['H'],
        period: [1988, 1997],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 100],
        contributingNumber: 440,
        baselineFemalePercentage: 76,
        sampleAgeMean: 'unclear',
        baselineEducation: '56% elementary (approx)',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: 3,
        followUpYears: [9, 'mean 5'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 163,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, gender, childhood school grades',
        effectSize: [0.73, 0.51, 1.04],
        educationSubcategory: 'secondary education',
        referenceSubcategory: 'elementary education'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.94, 0.55, 1.61],
        educationSubcategory: 'post-secondary and university',
        referenceSubcategory: 'elementary education'
      },
      {
        publicationYear: 2015, firstAuthor: 'Dekhtyar', studyName: 'Uppsala Birth Cohort', country: 'SE', context: ['H'],
        period: [1980, 2008],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 7574,
        baselineFemalePercentage: 46,
        sampleAgeMean: 'unclear',
        baselineEducation: '64% elementary',
        usedDiagnosticCriteria: false,  screenedBeforeClinicalEvaluation: false,
        numFollowUps: null,
        followUpYears: [21, 'range 14-28'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 950,
        measureOfEffect: ['HR'],
        adjustedFor: 'calendar year during follow up, birth cohort, sex, childhood grades, occupational complexity',
        effectSize: [0.95, 0.82, 1.10],
        educationSubcategory: 'senior high school',
        referenceSubcategory: 'elementary (up to 10 years)'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.87, 0.66, 1.15],
        educationSubcategory: 'professional/university',
        referenceSubcategory: 'elementary (up to 10 years)'
      },
      {
        publicationYear: 2018, firstAuthor: 'Sullivan', studyName: 'MoVIES and MYHAT', country: 'US', context: ['H'],
        period: [1987, 2017],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 3010,
        baselineFemalePercentage: 61,
        sampleAgeMean: '75.69 (6.93)',
        baselineEducation: '25.4% less than high school',
        usedDiagnosticCriteria: false,  screenedBeforeClinicalEvaluation: null, // todo true-false, //has a true and a false - is this possible?
        numFollowUps: 'unclear',
        followUpYears: ['unclear', 'mean 7.1'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 257,
        measureOfEffect: ['IRR'],
        adjustedFor: 'birth cohort, age, sex',
        effectSize: [0.88, 0.65, 1.19],
        educationSubcategory: 'high school graduate',
        referenceSubcategory: 'less than high school'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.77, 0.56, 1.07],
        educationSubcategory: 'college or higher',
        referenceSubcategory: 'less than high school'
      },
      {
        publicationYear: 2002, firstAuthor: 'Kukull', studyName: 'ACT', country: 'US', context: ['H'],
        period: [1994, 2000],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 2356,
        baselineFemalePercentage: 59.0,
        sampleAgeMean: '79.4 w/ dementia<br/>74.0 w/o dementia',
        baselineEducation: '12.8 w/ dementia<br/>13.9 w/o dementia',
        usedDiagnosticCriteria: true,  screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'presume 4'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 215,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex, APOE',
        effectSize: [0.85, 0.58, 1.24],
        educationSubcategory: '12-15 years',
        referenceSubcategory: '<12 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.64, 0.40, 1.00],
        educationSubcategory: '>15 years',
        referenceSubcategory: '<12 years'
      },
      // new section - high ed as base
      {
        category: 'High education base',
        publicationYear: 2005, firstAuthor: 'Ravaglia', studyName: 'CSBA', country: 'IT', context: ['H'],
        period: [1991, 2004],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 857,
        baselineFemalePercentage: 53.7,
        sampleAgeMean: '74 (6)',
        baselineEducation: '4.7 (2.4)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, '3.8 (0.8)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 115,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex',
        effectSize: [2.20, 1.07, 4.53],
        educationSubcategory: '<=3 years',
        referenceSubcategory: '6+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.19, 0.58, 2.46],
        educationSubcategory: '4-5 years',
        referenceSubcategory: '6+ years'
      },
       {
        publicationYear: 2011, firstAuthor: 'Lobo', studyName: 'Zarademp', country: 'ES', context: ['H'],
        period: [1994, 1999],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 2403,
        baselineFemalePercentage: 54.9,
        sampleAgeMean: '72.1 (9.1)',
        baselineEducation: '7.8% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, '4.5'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 138,
        measureOfEffect: ['IRR'],
        adjustedFor: 'age',
        effectSize: [2.82, 1.77, 4.35],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'primary'
      },
      {
        isSubcategoryRow: true,
        effectSize: [5.58, 2.73, 12.08],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'secondary school or higher'
      },
      {
        publicationYear: 1998, firstAuthor: 'Zhang', studyName: 'unknown', country: 'CN', context: ['LM'],
        period: [1987, 1992],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['RC'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1970,
        baselineFemalePercentage: 56,
        sampleAgeMean: 'unclear',
        baselineEducation: '29% 0 years',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 114,
        measureOfEffect: ['OR'],
        adjustedFor: 'age',
        effectSize: [2.23, 1.42, 3.51],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'elementary'
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.42, 1.56, 4.20],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'middle'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.15, 0.70, 1.89],
        educationSubcategory: 'elementary',
        referenceSubcategory: 'middle'
      },
      {
        publicationYear: 1998, firstAuthor: 'Nitrini', studyName: 'unknown', country: 'BR', context: ['LM'],
        period: [1997, 2000],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1119,
        baselineFemalePercentage: 58,
        sampleAgeMean: 'unclear',
        baselineEducation: '34.2% illiterate',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [3, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 50,
        measureOfEffect: ['IRR'],
        adjustedFor: 'unadjusted',
        effectSize: [2.01, 0.61, 6.58],
        educationSubcategory: '0 years (illiterate)',
        referenceSubcategory: '8 or more years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.16, 0.34, 3.94],
        educationSubcategory: '1-3 years',
        referenceSubcategory: '8 or more years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.39, 0.40, 4.89],
        educationSubcategory: '4-7 years',
        referenceSubcategory: '8 or more years'
      },
      {
        publicationYear: 2018, firstAuthor: 'Nakahori', studyName: 'Toyama Dementia Survey', country: 'JP', context: ['HIC'],
        period: [2014, 2014],
        studyType: ['CC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1176,
        baselineFemalePercentage: 57,
        sampleAgeMean: 'unclear',
        baselineEducation: '6.6% <=6 years',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: null,
        followUpYears: [null, null],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 137,
        measureOfEffect: ['OR'],
        adjustedFor: 'age, sex, lifestyle, medical history, SES',
        effectSize: [3.56, 1.90, 6.66],
        educationSubcategory: '<=6 years',
        referenceSubcategory: '>=10 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.92, 0.57, 1.50],
        educationSubcategory: '7-9 years',
        referenceSubcategory: '>=10 years'
      },
      {
        publicationYear: 2000, firstAuthor: 'Letenneur', studyName: 'EURODEM', country: 'DK-FR-NL-GB', context: ['H'],
        period: [1988, 1996],
        studyType: ['PC'],
        sampling: ['A', 'R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 12647,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: '37.6% low',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [3, '2.24(0.73)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 493,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, age x age, study, sex, history of MI, stroke, smoking',
        effectSize: [1.83, 1.16, 2.89],
        educationSubcategory: '<=7 years',
        referenceSubcategory: '>=12 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.32, 0.85, 2.05],
        educationSubcategory: '8-11 years',
        referenceSubcategory: '>= 12 years'
      },
      {
        publicationYear: 2011, firstAuthor: 'De Deyn', studyName: 'ANCOG', country: 'BE', context: ['H'],
        period: [null, null],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [75, 80],
        contributingNumber: 636,
        baselineFemalePercentage: 62.9,
        sampleAgeMean: '77.6 (1.52)',
        baselineEducation: '42.5% 1-8 years',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [3, 'approx'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 72,
        measureOfEffect: ['IRR'],
        adjustedFor: 'unadjusted',
        effectSize: [4.18, 1.52, 16.08],
        educationSubcategory: '1-8 years',
        referenceSubcategory: '>12 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.20, 0.77, 8.67],
        educationSubcategory: '9-12 years',
        referenceSubcategory: '>12 years'
      },
      {
        publicationYear: 2016, firstAuthor: 'Ojagbemi', studyName: 'ISA', country: 'NG', context: ['L'],
        period: [2003, 2009],
        studyType: ['PC'],
        sampling: ['RC'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 1894,
        baselineFemalePercentage: 54,
        sampleAgeMean: '74.4 (8.8)',
        baselineEducation: '55.1% 0 years',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [5, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 136,
        measureOfEffect: ['HR'],
        adjustedFor: 'unadjusted',
        effectSize: [0.90, 0.50, 1.90],
        educationSubcategory: '0 years',
        referenceSubcategory: '>=13 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.00, 0.50, 2.10],
        educationSubcategory: '1-6 years',
        referenceSubcategory: '>=13 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.00, 0.50, 2.20],
        educationSubcategory: '7-12 years',
        referenceSubcategory: '>=13 years'
      },
       {
        publicationYear: 2007, firstAuthor: 'McDowell', studyName: 'CSHA', country: 'CA', context: ['H'],
        period: [1991, 2001],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 5177,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [10, null],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 783,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex, marital status, income, occupational attainment, health problems, exercise, alcohol, smoking',
        effectSize: [2.00, 1.49, 2.67],
        educationSubcategory: '<6 years',
        referenceSubcategory: '13+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.30, 1.02, 1.70],
        educationSubcategory: '6-8 years',
        referenceSubcategory: '13+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.20, 0.93, 1.44],
        educationSubcategory: '9-12 years',
        referenceSubcategory: '13+ years'
      },
      {
        publicationYear: 2011, firstAuthor: 'Chen', studyName: 'Anhui', country: 'CN', context: ['LM'],
        period: [2001, 2009],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['Ex'], // excluded rural aged <65 and illiterate
        sampleAgeRecruited: [60, 100],
        contributingNumber: 1307,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [7.5, 'median 3.9'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 80,
        measureOfEffect: ['OR'],
        adjustedFor: 'unclear - possibly age, sex, BMI, urban/rural, occupation, income, smoking',
        effectSize: [2.12, 1.03, 4.38],
        educationSubcategory: 'primary school',
        referenceSubcategory: '>= high secondary school'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.35, 0.70, 2.61],
        educationSubcategory: 'secondary school',
        referenceSubcategory: '>= high secondary school'
      },
      {
        publicationYear: 2008, firstAuthor: 'Bermejo-Pareja', studyName: 'NEDICES', country: 'ES', context: ['H'],
        period: [1994, 1998],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 3891,
        baselineFemalePercentage: 57,
        sampleAgeMean: '79.5 (6.8)',
        baselineEducation: '30.4% illiterate cases<br/> 11.3% illiterate controls',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [6, 'mean 3.2 (range 0.03 - 6.6)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 161,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, current smoker, current ethanol consumption, stroke, diabetes mellitus, hypertension, heart disease, depressive symptoms',
        effectSize: [2.71, 1.46, 5.02],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.27, 0.70, 2.29],
        educationSubcategory: 'can read and write',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.01, 0.53, 1.92],
        educationSubcategory: 'primary studies',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        publicationYear: 1997, firstAuthor: 'Schmand - B', studyName: 'AMSTEL', country: 'NL', context: ['H'],
        period: [1990, 1994],
        studyType: ['PC'],
        sampling: [],
        populationRecruited: ['H'],
        sampleAgeRecruited: [65, 85],
        contributingNumber: 1950,
        baselineFemalePercentage: 62.4,
        sampleAgeMean: '75.4 (5.7)',
        baselineEducation: '8.2 (2.5)',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [4, null],
        riskOfBias: LowMedHigh.High,
        numberIncidentCases: 148,
        measureOfEffect: ['OR'],
        adjustedFor: 'age and sex',
        effectSize: [1.76, 0.48, 6.36],
        educationSubcategory: 'incomplete primary (<6 years)',
        referenceSubcategory: 'higher levels (11-18 years)'
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.19, 1.05, 4.59],
        educationSubcategory: 'primary (6 years)',
        referenceSubcategory: 'higher levels (11-18 years)'
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.19, 0.93, 5.14],
        educationSubcategory: 'extended primary (7-8 years)',
        referenceSubcategory: 'higher levels (11-18 years)'
      },
      {
        isSubcategoryRow: true,
        effectSize: [2.31, 1.06, 5.01],
        educationSubcategory: 'lower vocational (9-10 years)',
        referenceSubcategory: 'higher levels (11-18 years)'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.77, 0.32, 1.86],
        educationSubcategory: 'general intermediate (10-12 years)',
        referenceSubcategory: 'higher levels (11-18 years)'
      },
      {
        publicationYear: 2015, firstAuthor: 'de Bruijn', studyName: 'Rotterdam - original cohort', country: 'NL', context: ['H'],
        period: [1990, 2003],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 7003,
        baselineFemalePercentage: 59.8,
        sampleAgeMean: '69.4 (9.1)',
        baselineEducation: '54.3% low',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [12, 'mean 8.3 (2.9)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 624,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, BMI, hypertension, DM, total/HDL cholesterol ratio, lipid-lowering meds, smoking',
        effectSize: [1.13, 0.78, 1.63],
        educationSubcategory: 'low (primary or lower vocational)',
        referenceSubcategory: 'high (higher vocational or university)'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.99, 0.68, 1.45],
        educationSubcategory: 'intermediate (secondary or intermediate vocational)',
        referenceSubcategory: 'high (higher vocational or university)'
      },
      {
        publicationYear: 2015, firstAuthor: 'de Bruijn', studyName: 'Rotterdam - extended cohort', country: 'NL', context: ['H'],
        period: [2000, 2012],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 2593,
        baselineFemalePercentage: 56.2,
        sampleAgeMean: '65.0 (8.3)',
        baselineEducation: '33.7% low',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 3,
        followUpYears: [12, 'mean 8.9 (2.3)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 145,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, BMI, hypertension, DM, total/HDL cholesterol ratio, lipid-lowering meds, smoking',
        effectSize: [1.32, 0.73, 2.36],
        educationSubcategory: 'low (primary or lower vocational)',
        referenceSubcategory: 'high (higher vocational or university)'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.01, 0.57, 1.78],
        educationSubcategory: 'intermediate (secondary or intermediate vocational)',
        referenceSubcategory: 'high (higher vocational or university)'
      },
      {
        publicationYear: 2018, firstAuthor: 'Cadar', studyName: 'ELSA', country: 'GB', context: ['H'],
        period: [2002, 2015],
        studyType: ['PC'],
        sampling: [],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 6220,
        baselineFemalePercentage: 54.8,
        sampleAgeMean: '73.2',
        baselineEducation: '52.5% no qualification',
        usedDiagnosticCriteria: false, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 7,
        followUpYears: [12, null],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 463,
        measureOfEffect: ['HR'],
        adjustedFor: 'wealth, deprivation index, sex, marital status, stroke, hypertension, diabetes, CVD',
        effectSize: [0.92, 0.70, 1.23],
        educationSubcategory: 'no qualification',
        referenceSubcategory: 'university degree'
      },
       {
        isSubcategoryRow: true,
        effectSize: [0.74, 0.44, 1.22],
        educationSubcategory: '<A-level',
        referenceSubcategory: 'university degree'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.84, 0.62, 1.14],
        educationSubcategory: 'A-level',
        referenceSubcategory: 'university degree'
      },
    ];
  }

  // ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  public getCategoricalDataVascularDementia(): any[] {
    return [
      {
        // first section - low ed as base
        category: 'Low ed. base',
        publicationYear: 2016, firstAuthor: 'Yuan', studyName: 'unknown', country: 'CN', context: ['LM'],
        period: [1997, 2002],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [55, 100],
        contributingNumber: 12881,
        baselineFemalePercentage: 53.4,
        sampleAgeMean: 'unclear',
        baselineEducation: '34.9% 1-6 years',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [4, 'mean 3.1 (range 2.9 - 3.5)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 91,
        measureOfEffect: ['HR'],
        adjustedFor: 'age group, gender, residence status, region east vs west',
        effectSize: [0.60, 0.36, 1.02],
        educationSubcategory: '1-6 years',
        referenceSubcategory: '<1 year'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.32, 0.13, 0.76],
        educationSubcategory: '7-12 years',
        referenceSubcategory: '<1 year'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.11, 0.02, 0.86],
        educationSubcategory: '12+ years',
        referenceSubcategory: '<1 year'
      },
      {
        publicationYear: 2002, firstAuthor: 'Di Carlo', studyName: 'ILSA', country: 'IT', context: ['H'],
        period: [1992, 1995],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 84],
        contributingNumber: 2498,
        baselineFemalePercentage: 47.0,
        sampleAgeMean: '74.0 (5.6)',
        baselineEducation: '6.1 (4.6)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, 'mean 3.8 (0.9)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 34,
        measureOfEffect: ['HR'],
        adjustedFor: 'age and "demographic variables"',
        effectSize: [0.33, 0.08, 1.37],
        educationSubcategory: '6-10 years',
        referenceSubcategory: '0-5 years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.47, 0.14, 1.58],
        educationSubcategory: '>=11 years',
        referenceSubcategory: '0-5 years'
      },
      {
        // second section - high ed as base
        category: 'High ed. base',
        publicationYear: 2005, firstAuthor: 'Ravaglia', studyName: 'CSBA', country: 'IT', context: ['H'],
        period: [1991, 2004],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 857,
        baselineFemalePercentage: 53.7,
        sampleAgeMean: '74 (6)',
        baselineEducation: '4.7 (2.4)',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 1,
        followUpYears: [4, '3.8 (0.8)'],
        riskOfBias: LowMedHigh.Medium,
        numberIncidentCases: 34,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex',
        effectSize: [1.85, 0.52, 6.60],
        educationSubcategory: '<=3 years',
        referenceSubcategory: '6+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.12, 0.32, 3.96],
        educationSubcategory: '4-5 years',
        referenceSubcategory: '6+ years'
      },
      {
        publicationYear: 2007, firstAuthor: 'McDowell', studyName: 'CSHA', country: 'CA', context: ['H'],
        period: [1991, 2001],
        studyType: ['PC'],
        sampling: ['R'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 5177,
        baselineFemalePercentage: null,
        sampleAgeMean: 'unclear',
        baselineEducation: 'unclear',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: true,
        numFollowUps: 2,
        followUpYears: [10, null],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 163,
        measureOfEffect: ['RR'],
        adjustedFor: 'age, sex, marital status, income, occupational attainment, health problems, exercise, alcohol, smoking',
        effectSize: [2.10, 1.16, 3.74],
        educationSubcategory: '<6 years',
        referenceSubcategory: '13+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.80, 0.43, 1.34],
        educationSubcategory: '6-8 years',
        referenceSubcategory: '13+ years'
      },
      {
        isSubcategoryRow: true,
        effectSize: [1.00, 0.61, 1.56],
        educationSubcategory: '9-12 years',
        referenceSubcategory: '13+ years'
      },
      {
        publicationYear: 2008, firstAuthor: 'Bermejo-Pareja', studyName: 'NEDICES', country: 'ES', context: ['H'],
        period: [1994, 1998],
        studyType: ['PC'],
        sampling: ['A'],
        populationRecruited: ['C'],
        sampleAgeRecruited: [65, 100],
        contributingNumber: 3891,
        baselineFemalePercentage: 57,
        sampleAgeMean: '79.5 (6.8)',
        baselineEducation: '30.4% illiterate cases<br/> 11.3% illiterate controls',
        usedDiagnosticCriteria: true, screenedBeforeClinicalEvaluation: false,
        numFollowUps: 1,
        followUpYears: [6, 'mean 3.2 (range 0.03 - 6.6)'],
        riskOfBias: LowMedHigh.Low,
        numberIncidentCases: 18,
        measureOfEffect: ['HR'],
        adjustedFor: 'age, sex, current smoker, current ethanol consumption, stroke, diabetes mellitus, hypertension, heart disease, depressive symptoms',
        effectSize: [1.83, 0.41, 8.13],
        educationSubcategory: 'illiterate',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.33, 0.07, 1.54],
        educationSubcategory: 'can read and write',
        referenceSubcategory: 'secondary or higher studies'
      },
      {
        isSubcategoryRow: true,
        effectSize: [0.48, 0.09, 2.46],
        educationSubcategory: 'primary studies',
        referenceSubcategory: 'secondary or higher studies'
      },
    ];
  }
}
